### ISSUE TITLE
数组维度问题

### ISSUE THREAD

**Issue by xuridongshengpxd** [Huang-ShiRui/Semi-UIR#9]
恭喜您做的这个杰出的工作
我在运行train.py的时候出现如下报错：
there are total 200 batches for train
there are total 52 batches for val
student model params: 1675281
/home/C/pxd/.conda/envs/test/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/C/pxd/.conda/envs/test/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading pretrained model MUSIQ from /home/C/pxd/.cache/torch/hub/checkpoints/musiq_koniq_ckpt-e95806b9.pth
/home/C/pxd/.conda/envs/test/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
  0%|                                                                                                     | 0/200 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/C/pxd/Semi-UIR/train.py", line 62, in <module>
    main(-1, args)
  File "/home/C/pxd/Semi-UIR/train.py", line 40, in main
    trainer.train()
  File "/home/C/pxd/Semi-UIR/trainer.py", line 98, in train
    loss_ave, psnr_train = self._train_epoch(epoch)
  File "/home/C/pxd/Semi-UIR/trainer.py", line 152, in _train_epoch
    p_sample = self.get_reliable(predict_target_u, outputs_ul, p_list, p_name, score_r)
  File "/home/C/pxd/Semi-UIR/trainer.py", line 78, in get_reliable
    if score_t[idx] > score_s[idx]:
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

请问这种情况您遇到过吗？如何解决呀？！

**Comment by Huang-ShiRui** [comment]
我没有遇到过，你有改过代码里面的哪些部分吗？score_t和score_s都是数组，长度和batchsize一致，报这个错是数组维度的问题，可能1）设置的batchsize是1；2）score_t和score_s都是常量而不是数组了；3）其他原因，都排查一遍

**Comment by haomingziranggeizhu** [comment]
我也遇到了同样的问题，musiq输入一个batch输出的是一个数字不知道原因

**Comment by haomingziranggeizhu** [comment]
我解决了问题，bug是出在每次传入musiq的时候是只传入了batch里第一个数据，后面的没有传进去，写一个for循环按照0维度遍历一下就行了

**Comment by tamshawn** [comment]
> 我解决了问题，bug是出在每次传入musiq的时候是只传入了batch里第一个数据，后面的没有传进去，写一个for循环按照0维度遍历一下就行了

你好，我也遇到了相同的问题，请问是get_reliable函数中给score_t和score_s赋值时的循环吗，具体要怎么弄呢

**Comment by tamshawn** [comment]
> 可能是因为版本问题，musiq函数每次都只能传入batch里的第一个数据，剩下的不会传进去，你写个for循环，在B维度把batch里的参数一个一个读到musiq函数里，然后再拼成一个ndarray就行

确实是这样，谢谢哈，我已经跑通了

**Comment by yudongLi0729** [comment]
> 可能是因为版本问题，musiq函数每次都只能传入batch里的第一个数据，剩下的不会传进去，你写个for循环，在B维度把batch里的参数一个一个读到musiq函数里，然后再拼成一个ndarray就行

您好，可以提供一下修改的那部分代码吗？十分感谢
